Update plate_solver.py
len() expects a list-like object, but h.keys() is not a list, hence the error:
TypeError: object of type 'generator' has no len()

This is solved by changing from len() to any(). Platesolve now works.